[allowlist]
  paths = [
    '''saml-core/src/test/java/org/iamshield/saml/processing/core/saml/v2/util/AssertionUtilTest.java''',
    '''services/src/test/java/org/iamshield/protocol/oidc/utils/RedirectUtilsTest.java'''


  ]
  
  regexes = [
    '''H0JaTc7VBu3HJR26vrzMxgidfJmgI5Dw'''
  ]
